# Copy this file to the parent directory of the repopopulate
# Populate the variables
# Rename this file to config.yaml

credentials:
    vm_username: 'Administrator'
    vm_password: 'example_password'
    smb_domain: 'relativity'
    smb_username: 'my_user_name'
    smb_password: 'example_network_password'

email:
    smtp_server: 'smtp.relativity.com'
    smtp_port: '25'
    email_from: 'noreply@relativity.com'
    email_to: 'test.user1@relativity.com;test.user2@relativity.com'
